# Inventory Transfer Demo
# Uses PostgreSQL inside Docker container. No local psql required.

$ErrorActionPreference = "Stop"

$PgUser = "admin"
$Database = "inventory_db"

$ProductId = "a0000000-0000-0000-0000-000000000001"
$ProductCode = "AB-ARR-001"
$SourceBranchId = "33333333-3333-3333-3333-333333333331"
$DestinationBranchId = "33333333-3333-3333-3333-333333333332"

function Invoke-Psql {
    param(
        [string]$Sql,
        [switch]$Scalar
    )

    if ($Scalar) {
        $rawResult = $Sql | docker compose exec -T postgres psql -q -v ON_ERROR_STOP=1 -U $PgUser -d $Database -t -A
        $textResult = ($rawResult | Out-String).Trim()

        $uuidMatch = [regex]::Match(
            $textResult,
            "[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}"
        )

        if ($uuidMatch.Success) {
            return $uuidMatch.Value
        }

        return $textResult
    }

    $Sql | docker compose exec -T postgres psql -v ON_ERROR_STOP=1 -U $PgUser -d $Database

    if ($LASTEXITCODE -ne 0) {
        throw "psql command failed."
    }
}

function Show-Stock {
    param([string]$Title)

    Write-Host ""
    Write-Host $Title -ForegroundColor Cyan

    Invoke-Psql -Sql @"
SELECT
    branch_id,
    product_id,
    product_code,
    product_name_snapshot,
    quantity,
    min_stock,
    CASE
        WHEN quantity <= min_stock THEN 'STOCK_LOW'
        ELSE 'STOCK_OK'
    END AS stock_status
FROM inventory_stock
WHERE product_id = '$ProductId'
ORDER BY branch_id;
"@
}

Write-Host "Starting Inventory Transfer Demo..." -ForegroundColor Cyan

Write-Host ""
Write-Host "Resetting inventory demo stock from seed..." -ForegroundColor Cyan

# Clean previous transfer demo data to avoid noise
"DELETE FROM inventory_transfer_details; DELETE FROM inventory_transfers;" |
    docker compose exec -T postgres psql -v ON_ERROR_STOP=1 -U $PgUser -d $Database

Get-Content -Raw "database\service-databases\inventory-db\02-seed.sql" |
    docker compose exec -T postgres psql -v ON_ERROR_STOP=1 -U $PgUser -d $Database

if ($LASTEXITCODE -ne 0) {
    throw "Could not reset inventory seed."
}

Show-Stock "Step 1: Initial stock for product $ProductCode"

Write-Host ""
Write-Host "Step 2: Creating transfer request from Central to Zona Norte..." -ForegroundColor Cyan

$TransferId = Invoke-Psql -Scalar -Sql @"
INSERT INTO inventory_transfers (
    source_branch_id,
    destination_branch_id,
    status,
    notes
)
VALUES (
    '$SourceBranchId',
    '$DestinationBranchId',
    'PENDING',
    'Demo transfer generated by DBB script'
)
RETURNING id;
"@

Write-Host "Transfer created: $TransferId" -ForegroundColor Green

Invoke-Psql -Sql @"
INSERT INTO inventory_transfer_details (
    transfer_id,
    product_id,
    quantity
)
VALUES (
    '$TransferId',
    '$ProductId',
    10
);
"@

Write-Host ""
Write-Host "Step 3: Dispatching transfer..." -ForegroundColor Cyan

Invoke-Psql -Sql "SELECT process_inventory_transfer_dispatch('$TransferId');"

Write-Host ""
Write-Host "Transfer status after dispatch:" -ForegroundColor Cyan
Invoke-Psql -Sql "SELECT id, source_branch_id, destination_branch_id, status, dispatched_at FROM inventory_transfers WHERE id = '$TransferId';"

Show-Stock "Stock after dispatch"

Write-Host ""
Write-Host "Step 4: Receiving transfer..." -ForegroundColor Cyan

Invoke-Psql -Sql "SELECT process_inventory_transfer_receive('$TransferId');"

Write-Host ""
Write-Host "Transfer status after receive:" -ForegroundColor Cyan
Invoke-Psql -Sql "SELECT id, source_branch_id, destination_branch_id, status, dispatched_at, received_at FROM inventory_transfers WHERE id = '$TransferId';"

Show-Stock "Step 5: Final stock after receive"

Write-Host ""
Write-Host "Step 6: Kardex history for transferred product..." -ForegroundColor Cyan

Invoke-Psql -Sql @"
SELECT
    branch_id,
    product_id,
    transaction_type,
    quantity_change,
    balance_after,
    created_at
FROM v_inventory_kardex_history
WHERE product_id = '$ProductId'
ORDER BY created_at DESC
LIMIT 10;
"@

Write-Host ""
Write-Host "Step 7: Validating insufficient stock control..." -ForegroundColor Cyan

$InvalidTransferId = Invoke-Psql -Scalar -Sql @"
INSERT INTO inventory_transfers (
    source_branch_id,
    destination_branch_id,
    status,
    notes
)
VALUES (
    '$SourceBranchId',
    '$DestinationBranchId',
    'PENDING',
    'Expected failure demo: insufficient stock'
)
RETURNING id;
"@

Invoke-Psql -Sql @"
INSERT INTO inventory_transfer_details (
    transfer_id,
    product_id,
    quantity
)
VALUES (
    '$InvalidTransferId',
    '$ProductId',
    99999
);
"@

Write-Host "Trying to dispatch transfer with impossible quantity. This should fail:" -ForegroundColor Yellow

$ErrorActionPreference = "Continue"
"SELECT process_inventory_transfer_dispatch('$InvalidTransferId');" |
    docker compose exec -T postgres psql -v ON_ERROR_STOP=1 -U $PgUser -d $Database
$dispatchExitCode = $LASTEXITCODE
$ErrorActionPreference = "Stop"

if ($dispatchExitCode -ne 0) {
    Write-Host "OK: Insufficient stock was correctly rejected." -ForegroundColor Green
} else {
    Write-Host "WARNING: Insufficient stock was not rejected. Review function logic." -ForegroundColor Yellow
}

Write-Host ""
Write-Host "Inventory transfer demo completed." -ForegroundColor Green
